# Generated by Django 2.2.9 on 2020-02-27 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='describe_yourself',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='dog_firstaid_and_or_CPR',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male  '), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('PETSITTING', 'Pet Sitter'), ('WALKING', 'Walker'), ('TRAINING', 'Trainer'), ('FULL', 'FULL')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_of_any_organisation',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='overnight_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pet_preference',
            field=models.CharField(blank=True, choices=[('DOGS', 'Dog'), ('CATS', 'Cat'), ('DOGS&CAT', 'Both')], default='DOGS', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='your_photos_with_pets',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
