# Generated by Django 2.2.9 on 2020-06-02 14:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_colour', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_age', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Invalid', 'Invalid'), ('Out for delivery', 'Out for delivery')], default='Received', max_length=16)),
                ('message', models.CharField(default='Information Received, Kindly Check Again After Sometime for further updates!', max_length=1000)),
                ('pet_gender', models.CharField(blank=True, choices=[('Male', 'Male  '), ('Female', 'Female')], default='Male', max_length=10)),
                ('pet_type', models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat')], default='Dog', max_length=3)),
                ('application_preference', models.CharField(blank=True, choices=[('Renew', 'Renew'), ('New', 'New')], default='New', max_length=5)),
                ('old_license', models.FileField(blank=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('vaccination_record', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('address_proof', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
