# Generated by Django 2.2.9 on 2020-04-28 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petcab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('depart_at', models.TimeField()),
                ('ride_date', models.DateTimeField()),
                ('no_of_travellers', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('B', 'Booked'), ('P', 'Pending')], default='Pending', max_length=2)),
                ('message', models.CharField(default='Please Check Again After Some Time', max_length=1000)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
